sonar.projectKey=adm01-debug_Departamento_Pessoal_V3
sonar.organization=adm01-debug
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.cpd.exclusions=supabase/migrations/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.sourceEncoding=UTF-8
