// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { rewriteFunctionsUrl } from '@/lib/functionsUrl';


// Projeto ativo: variáveis de ambiente são obrigatórias (P0-008).
// Sem fallback hardcoded — qualquer ausência falha o build com mensagem clara.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '[SUPABASE] VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY) ' +
      'são obrigatórias. Configure no .env antes do build. Veja .env.example.',
  );
}

// P0-CORS-BYEMOM: o proxy `supabase` que roteava `.from()`/`.rpc()` via edge
// function `external-db-bridge` foi REMOVIDO. O gateway do Supabase Cloud
// estava reescrevendo o header `Access-Control-Allow-Origin` para
// `https://sistema-dp.lovable.app` em respostas autenticadas da edge function,
// bloqueando TODAS as queries feitas de `http://localhost:8080`.
//
// Agora `supabase` É `supabaseBase` (mesma instância). Toda requisição vai
// direto pelo PostgREST em `/rest/v1/...`, que bypassa o gateway e respeita
// o RLS do V2. O resultado tem o mesmo formato `{ data, error, count }` que
// o resto do projeto já espera.
// Em dev, `supabase.functions.invoke()` monta a URL internamente a partir de
// SUPABASE_URL e vai direto ao gateway do Supabase — que devolve
// Access-Control-Allow-Origin fixo (sistema-dp.lovable.app) e faz o navegador
// bloquear toda chamada vinda de localhost. Reescrevendo a URL aqui, os 37
// pontos de `functions.invoke()` do projeto passam pelo proxy do dev server
// (same-origin, sem CORS) sem precisar tocar em nenhum deles.
// Em produção `rewriteFunctionsUrl` é no-op — a URL absoluta é preservada.
const functionsAwareFetch: typeof fetch = (input, init) => {
  if (typeof input === 'string') return fetch(rewriteFunctionsUrl(input), init);
  if (input instanceof URL) return fetch(rewriteFunctionsUrl(input.toString()), init);
  if (input instanceof Request) {
    const rewritten = rewriteFunctionsUrl(input.url);
    return rewritten === input.url ? fetch(input, init) : fetch(new Request(rewritten, input), init);
  }
  return fetch(input, init);
};

export const supabaseBase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'},
    global: { fetch: functionsAwareFetch }
  }
);

export const supabase = supabaseBase;